/**
 * Confckurator
 * Confckurator Client/Server API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/// <reference path="api.d.ts" />

/* tslint:disable:no-unused-variable member-ordering */

namespace API.Client {
    'use strict';

    export class PacksApi {
        protected basePath = 'https://localhost/api';
        public defaultHeaders : any = {};

        static $inject: string[] = ['$http', '$httpParamSerializer', 'basePath'];

        constructor(protected $http: ng.IHttpService, protected $httpParamSerializer?: (d: any) => any, basePath?: string) {
            if (basePath !== undefined) {
                this.basePath = basePath;
            }
        }

        private extendObj<T1,T2>(objA: T1, objB: T2) {
            for(let key in objB){
                if(objB.hasOwnProperty(key)){
                    objA[key] = objB[key];
                }
            }
            return <T1&T2>objA;
        }

        /**
         * Create a new pack
         * 
         * @param postPacksBody Pack creation properties.
         */
        public createPack (postPacksBody?: NewPack, extraHttpRequestParams?: any ) : ng.IHttpPromise<IdResponse> {
            const localVarPath = this.basePath + '/pack/';

            let queryParameters: any = {};
            let headerParams: any = this.extendObj({}, this.defaultHeaders);
            let httpRequestParams: any = {
                method: 'POST',
                url: localVarPath,
                json: true,
                data: postPacksBody,
                                params: queryParameters,
                headers: headerParams
            };

            if (extraHttpRequestParams) {
                httpRequestParams = this.extendObj(httpRequestParams, extraHttpRequestParams);
            }

            return this.$http(httpRequestParams);
        }
        /**
         * Delete a pack
         * 
         * @param packId The pack ID.
         */
        public deletePack (packId: number, extraHttpRequestParams?: any ) : ng.IHttpPromise<any> {
            const localVarPath = this.basePath + '/pack/{packId}'
                .replace('{' + 'packId' + '}', String(packId));

            let queryParameters: any = {};
            let headerParams: any = this.extendObj({}, this.defaultHeaders);
            // verify required parameter 'packId' is not null or undefined
            if (packId === null || packId === undefined) {
                throw new Error('Required parameter packId was null or undefined when calling deletePack.');
            }
            let httpRequestParams: any = {
                method: 'DELETE',
                url: localVarPath,
                json: true,
                                                params: queryParameters,
                headers: headerParams
            };

            if (extraHttpRequestParams) {
                httpRequestParams = this.extendObj(httpRequestParams, extraHttpRequestParams);
            }

            return this.$http(httpRequestParams);
        }
        /**
         * Delete a variable&#39;s value
         * 
         * @param packId The pack ID.
         * @param variableId The variable ID.
         * @param setVariableValue Variable value.
         */
        public deletePackValue (packId: number, variableId: number, setVariableValue?: DeleteVariableValue, extraHttpRequestParams?: any ) : ng.IHttpPromise<any> {
            const localVarPath = this.basePath + '/pack/{packId}/variable/{variableId}'
                .replace('{' + 'packId' + '}', String(packId))
                .replace('{' + 'variableId' + '}', String(variableId));

            let queryParameters: any = {};
            let headerParams: any = this.extendObj({}, this.defaultHeaders);
            // verify required parameter 'packId' is not null or undefined
            if (packId === null || packId === undefined) {
                throw new Error('Required parameter packId was null or undefined when calling deletePackValue.');
            }
            // verify required parameter 'variableId' is not null or undefined
            if (variableId === null || variableId === undefined) {
                throw new Error('Required parameter variableId was null or undefined when calling deletePackValue.');
            }
            let httpRequestParams: any = {
                method: 'DELETE',
                url: localVarPath,
                json: true,
                data: setVariableValue,
                                params: queryParameters,
                headers: headerParams
            };

            if (extraHttpRequestParams) {
                httpRequestParams = this.extendObj(httpRequestParams, extraHttpRequestParams);
            }

            return this.$http(httpRequestParams);
        }
        /**
         * Get details about a pack
         * 
         * @param packId The pack ID.
         */
        public getPack (packId: number, extraHttpRequestParams?: any ) : ng.IHttpPromise<Pack> {
            const localVarPath = this.basePath + '/pack/{packId}'
                .replace('{' + 'packId' + '}', String(packId));

            let queryParameters: any = {};
            let headerParams: any = this.extendObj({}, this.defaultHeaders);
            // verify required parameter 'packId' is not null or undefined
            if (packId === null || packId === undefined) {
                throw new Error('Required parameter packId was null or undefined when calling getPack.');
            }
            let httpRequestParams: any = {
                method: 'GET',
                url: localVarPath,
                json: true,
                                                params: queryParameters,
                headers: headerParams
            };

            if (extraHttpRequestParams) {
                httpRequestParams = this.extendObj(httpRequestParams, extraHttpRequestParams);
            }

            return this.$http(httpRequestParams);
        }
        /**
         * Get an instantiated pack
         * 
         * @param packId The pack ID.
         * @param environmentId The environment ID.
         */
        public getPackInstance (packId: number, environmentId: number, extraHttpRequestParams?: any ) : ng.IHttpPromise<PackInstance> {
            const localVarPath = this.basePath + '/instance/{packId}/{environmentId}'
                .replace('{' + 'packId' + '}', String(packId))
                .replace('{' + 'environmentId' + '}', String(environmentId));

            let queryParameters: any = {};
            let headerParams: any = this.extendObj({}, this.defaultHeaders);
            // verify required parameter 'packId' is not null or undefined
            if (packId === null || packId === undefined) {
                throw new Error('Required parameter packId was null or undefined when calling getPackInstance.');
            }
            // verify required parameter 'environmentId' is not null or undefined
            if (environmentId === null || environmentId === undefined) {
                throw new Error('Required parameter environmentId was null or undefined when calling getPackInstance.');
            }
            let httpRequestParams: any = {
                method: 'GET',
                url: localVarPath,
                json: true,
                                                params: queryParameters,
                headers: headerParams
            };

            if (extraHttpRequestParams) {
                httpRequestParams = this.extendObj(httpRequestParams, extraHttpRequestParams);
            }

            return this.$http(httpRequestParams);
        }
        /**
         * List all packs
         * 
         */
        public getPacks (extraHttpRequestParams?: any ) : ng.IHttpPromise<PackList> {
            const localVarPath = this.basePath + '/pack/';

            let queryParameters: any = {};
            let headerParams: any = this.extendObj({}, this.defaultHeaders);
            let httpRequestParams: any = {
                method: 'GET',
                url: localVarPath,
                json: true,
                                                params: queryParameters,
                headers: headerParams
            };

            if (extraHttpRequestParams) {
                httpRequestParams = this.extendObj(httpRequestParams, extraHttpRequestParams);
            }

            return this.$http(httpRequestParams);
        }
        /**
         * Set a variable&#39;s value
         * 
         * @param packId The pack ID.
         * @param variableId The variable ID.
         * @param setVariableValue Variable value.
         */
        public setPackValue (packId: number, variableId: number, setVariableValue?: VariableValueUpdate, extraHttpRequestParams?: any ) : ng.IHttpPromise<any> {
            const localVarPath = this.basePath + '/pack/{packId}/variable/{variableId}'
                .replace('{' + 'packId' + '}', String(packId))
                .replace('{' + 'variableId' + '}', String(variableId));

            let queryParameters: any = {};
            let headerParams: any = this.extendObj({}, this.defaultHeaders);
            // verify required parameter 'packId' is not null or undefined
            if (packId === null || packId === undefined) {
                throw new Error('Required parameter packId was null or undefined when calling setPackValue.');
            }
            // verify required parameter 'variableId' is not null or undefined
            if (variableId === null || variableId === undefined) {
                throw new Error('Required parameter variableId was null or undefined when calling setPackValue.');
            }
            let httpRequestParams: any = {
                method: 'POST',
                url: localVarPath,
                json: true,
                data: setVariableValue,
                                params: queryParameters,
                headers: headerParams
            };

            if (extraHttpRequestParams) {
                httpRequestParams = this.extendObj(httpRequestParams, extraHttpRequestParams);
            }

            return this.$http(httpRequestParams);
        }
    }
}
