/**
 * Confckurator
 * Confckurator Client/Server API
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Environment {
    id: number;

    name: string;

  /**
   * Wheter or not this environment is in use.
   */
  in_use: boolean;

}
