/**
 * Confckurator
 * Confckurator Client/Server API
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UpdateTemplateVariablesUpdate {
    id: number;

  /**
   * Unique name of the variable.
   */
  name?: string;

    description?: string;

}
