/**
 * Confckurator
 * Confckurator Client/Server API
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UpdateTemplateVariablesCreate {
  /**
   * Unique name of the variable.
   */
  name: string;

  /**
   * Variable description (e.g. constraints).
   */
  description: string;

}
