/**
 * Confckurator
 * Confckurator Client/Server API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Value {
    /**
     * Variable ID
     */
    variable_id: number;

    /**
     * Environment ID
     */
    environment_id: number;

    /**
     * Pack ID
     */
    pack_id: number;

    /**
     * Value data
     */
    data?: string;

}
