/**
 * Confckurator
 * Confckurator Client/Server API
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Variable {
    /**
     * Variable ID
     */
    id: number;

    /**
     * Unique (within its template) variable name.
     */
    name: string;

    /**
     * Description of this variable (i.e. constraints).
     */
    description: string;

    /**
     * Wheter or not this variable is in use.
     */
    in_use: boolean;

}
