/**
 * Confckurator
 * Confckurator Client/Server API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-variable member-ordering */

import {Inject, Injectable, Optional} from '@angular/core';
import {
  Headers,
  Http,
  RequestMethod,
  RequestOptions,
  RequestOptionsArgs,
  Response,
  URLSearchParams
} from '@angular/http';

import {Observable} from 'rxjs/Observable';
import 'rxjs/add/operator/map';

import * as models from '../model/models';
import {BASE_PATH} from '../variables';
import {Configuration} from '../configuration';


@Injectable()
export class PacksApi {

    protected basePath = 'https://localhost/api';
    public defaultHeaders: Headers = new Headers();
    public configuration: Configuration = new Configuration();

    constructor(protected http: Http, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
        }
    }

    /**
     *
     * @summary Attach a template to a pack
     * @param packId The pack ID.
     * @param templateId The template ID.
     */
    public attachPackTemplate(packId: number, templateId: number, extraHttpRequestParams?: any): Observable<any> {
        return this.attachPackTemplateWithHttpInfo(packId, templateId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     *
     * @summary Create a new pack
     * @param postPacksBody Pack creation properties.
     */
    public createPack(postPacksBody?: models.NewPack, extraHttpRequestParams?: any): Observable<models.IdResponse> {
        return this.createPackWithHttpInfo(postPacksBody, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     *
     * @summary Delete a pack
     * @param packId The pack ID.
     */
    public deletePack(packId: number, extraHttpRequestParams?: any): Observable<any> {
        return this.deletePackWithHttpInfo(packId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     *
     * @summary Delete a variable's value
     * @param packId The pack ID.
     * @param variableId The variable ID.
     * @param setVariableValue Variable value.
     */
    public deletePackValue(packId: number, variableId: number, setVariableValue?: models.DeleteVariableValue, extraHttpRequestParams?: any): Observable<any> {
        return this.deletePackValueWithHttpInfo(packId, variableId, setVariableValue, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     *
     * @summary Remove a template from a pack
     * @param packId The pack ID.
     * @param templateId The template ID.
     */
    public detachPackTemplate(packId: number, templateId: number, extraHttpRequestParams?: any): Observable<any> {
        return this.detachPackTemplateWithHttpInfo(packId, templateId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     *
     * @summary Get details about a pack
     * @param packId The pack ID.
     */
    public getPack(packId: number, extraHttpRequestParams?: any): Observable<models.Pack> {
        return this.getPackWithHttpInfo(packId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     *
     * @summary List all packs
     */
    public getPacks(extraHttpRequestParams?: any): Observable<Array<models.Pack>> {
        return this.getPacksWithHttpInfo(extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     *
     * @summary Set a variable's value
     * @param packId The pack ID.
     * @param variableId The variable ID.
     * @param setVariableValue Variable value.
     */
    public setPackValue(packId: number, variableId: number, setVariableValue?: models.VariableValueUpdate, extraHttpRequestParams?: any): Observable<any> {
        return this.setPackValueWithHttpInfo(packId, variableId, setVariableValue, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }


    /**
     * Attach a template to a pack
     *
     * @param packId The pack ID.
     * @param templateId The template ID.
     */
    public attachPackTemplateWithHttpInfo(packId: number, templateId: number, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/pack/${packId}/template/${templateId}'
                    .replace('${' + 'packId' + '}', String(packId))
                    .replace('${' + 'templateId' + '}', String(templateId));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'packId' is not null or undefined
        if (packId === null || packId === undefined) {
            throw new Error('Required parameter packId was null or undefined when calling attachPackTemplate.');
        }
        // verify required parameter 'templateId' is not null or undefined
        if (templateId === null || templateId === undefined) {
            throw new Error('Required parameter templateId was null or undefined when calling attachPackTemplate.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Create a new pack
     *
     * @param postPacksBody Pack creation properties.
     */
    public createPackWithHttpInfo(postPacksBody?: models.NewPack, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/pack/';

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Put,
            headers: headers,
            body: postPacksBody == null ? '' : JSON.stringify(postPacksBody), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Delete a pack
     *
     * @param packId The pack ID.
     */
    public deletePackWithHttpInfo(packId: number, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/pack/${packId}'
                    .replace('${' + 'packId' + '}', String(packId));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'packId' is not null or undefined
        if (packId === null || packId === undefined) {
            throw new Error('Required parameter packId was null or undefined when calling deletePack.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Delete,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Delete a variable&#39;s value
     *
     * @param packId The pack ID.
     * @param variableId The variable ID.
     * @param setVariableValue Variable value.
     */
    public deletePackValueWithHttpInfo(packId: number, variableId: number, setVariableValue?: models.DeleteVariableValue, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/pack/${packId}/variable/${variableId}'
                    .replace('${' + 'packId' + '}', String(packId))
                    .replace('${' + 'variableId' + '}', String(variableId));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'packId' is not null or undefined
        if (packId === null || packId === undefined) {
            throw new Error('Required parameter packId was null or undefined when calling deletePackValue.');
        }
        // verify required parameter 'variableId' is not null or undefined
        if (variableId === null || variableId === undefined) {
            throw new Error('Required parameter variableId was null or undefined when calling deletePackValue.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Delete,
            headers: headers,
            body: setVariableValue == null ? '' : JSON.stringify(setVariableValue), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Remove a template from a pack
     *
     * @param packId The pack ID.
     * @param templateId The template ID.
     */
    public detachPackTemplateWithHttpInfo(packId: number, templateId: number, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/pack/${packId}/template/${templateId}'
                    .replace('${' + 'packId' + '}', String(packId))
                    .replace('${' + 'templateId' + '}', String(templateId));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'packId' is not null or undefined
        if (packId === null || packId === undefined) {
            throw new Error('Required parameter packId was null or undefined when calling detachPackTemplate.');
        }
        // verify required parameter 'templateId' is not null or undefined
        if (templateId === null || templateId === undefined) {
            throw new Error('Required parameter templateId was null or undefined when calling detachPackTemplate.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Delete,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Get details about a pack
     *
     * @param packId The pack ID.
     */
    public getPackWithHttpInfo(packId: number, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/pack/${packId}'
                    .replace('${' + 'packId' + '}', String(packId));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'packId' is not null or undefined
        if (packId === null || packId === undefined) {
            throw new Error('Required parameter packId was null or undefined when calling getPack.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * List all packs
     *
     */
    public getPacksWithHttpInfo(extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/pack/';

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Set a variable&#39;s value
     *
     * @param packId The pack ID.
     * @param variableId The variable ID.
     * @param setVariableValue Variable value.
     */
    public setPackValueWithHttpInfo(packId: number, variableId: number, setVariableValue?: models.VariableValueUpdate, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/pack/${packId}/variable/${variableId}'
                    .replace('${' + 'packId' + '}', String(packId))
                    .replace('${' + 'variableId' + '}', String(variableId));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'packId' is not null or undefined
        if (packId === null || packId === undefined) {
            throw new Error('Required parameter packId was null or undefined when calling setPackValue.');
        }
        // verify required parameter 'variableId' is not null or undefined
        if (variableId === null || variableId === undefined) {
            throw new Error('Required parameter variableId was null or undefined when calling setPackValue.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Patch,
            headers: headers,
            body: setVariableValue == null ? '' : JSON.stringify(setVariableValue), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

}
